name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  RUNNER_VERSION: 2.280.3
jobs:

  build_and_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
  
    - name: Login to GH Docker
      uses: docker/login-action@v1
      with:
        username: lenisha
        password: ${{secrets.GITHUB_TOKEN}}
        registry: ghcr.io
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        build-args: |
          build_version=${{github.run_number}}
        tags: ghcr.io/${{GITHUB_REPOSITORY}}/github-runner:${{env.RUNNER_VERSION}}
        file: Dockerfile
  
       #cache-from: type=registry,ref=lenisha/devops-oh/api-poi:${{github.run_number}}
        #cache-to: type=inline
        
    
  
